### ISSUE TITLE
All photos already exists in the * folder

### ISSUE THREAD

**Issue by vexersa** [yash1th/unsplash-album-downloader#1] opened 2018-07-21 08:32 UTC
When issuing the command:

`python download_user_album.py USERNAME collections full`

Only the first folder is downloaded and the following is logged to console:

'all photos already exists in the Fatigue folder'

Expected operation:
Downloads all the collections.

Current operation:
Downloads one folder, subsequent requests to download additional items results in no change, even if additional collections are created, the same operation persists.

**Comment by yash1th** [comment] 2018-09-16 17:33
@vexersa I am not able to reproduce the issue. I am able to download all the collections of a particular user 
```sh
$ python download_user_album.py anthonytran collections full
successfully downloaded 4 photos in "Awesome" folder
successfully downloaded 5 photos in "Wonder" folder
successfully downloaded 26 photos in "Travel " folder
successfully downloaded 8 photos in "Portrait" folder

<img width="618" alt="image" src="https://user-images.githubusercontent.com/6474295/45599180-f669d300-b99b-11e8-9ea6-16532e63a9dc.png">

**Comment by yash1th** [comment] 2020-01-29 18:53
@vexersa I am closing this issue since I did not get any reply. Please reopen it if you are still facing this issue

**Closed by yash1th** 2020-01-29 18:53 UTC

**Comment by vexersa** [comment] 2020-01-30 09:45
No problem. Apologies, I somehow missed your reply. I am not sure if this issue is still present in my code, most likely not as I was n00b back then.

**Comment by yash1th** [comment] 2020-01-30 13:49
@vexersa not a problem. we all are :)
